version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"

  director-service:
    build:
      context: ./director-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  movie-service:
    build:
      context: ./movie-app
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
