### Get all directors

GET http://localhost:8081/api/directors

### Get single director

GET http://localhost:8081/api/directors/eae5bc91-b706-4e7f-a8d4-69c0acb5fce1

### Create new director

POST http://localhost:8081/api/directors
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Mel Gibson",
  "age": 60
}

### Delete director.

DELETE http://localhost:8081/api/directors/c56f8191-37c4-437a-afd0-a716b6a3dcf8

### Get all movies

GET http://localhost:8082/api/movies

### Get single movie

GET http://localhost:8081/api/movies/525d3e7b-bb1f-4c13-bf17-926d1a12e4c0

### Delete movie

DELETE http://localhost:8082/api/movies/f5875513-bf7b-4ae1-b8a5-5b70a1b90e76

