server:
  port: 8082


spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    ddl-auto: update
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true